version: "3.8"
services:
  postgres:
    container_name: booking_postgres
    image: postgres:latest
    restart: always
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: booking
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - 5432

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - backend
    expose:
      - 9000
    ports:
      - 9000:9000
    depends_on:
      - postgres
    volumes:
      - ./backend:/app

volumes:
  postgresql_data:

networks:
  backend:
